### ISSUE TITLE
Duplicate NendAdResource.bundle when append project in Unity 2019.3 

### ISSUE THREAD

**Issue by ha-quang-vu** [fan-ADN/nendSDK-Unity-pub#1]
In Unity 2019.3, when Build.
If using "Append" function, to appending to an old project, NendAdResource.bundle will be duplicate in "Target -> Build Phases ->Copy Bundle Resources"
No problem when using "Replace" function.

Thanks and Best Regards.

**Comment by fan-c-yu** [comment]
Hello @ha-quang-vu

Thank you for your inquiry.
We are considering to fix this porblem. 
As a provisional measure, We recommend using "Replace" function or delete the  "Copy Bundle Resources" setting manually on Xcode.

Thanks and Best Regards.
